version: '3.8'

services:

  web:
    image: # STAGING IMAGE NAME
    restart: unless-stopped
    ports:
      - 8000:8000
    command: sh -c ./scripts/entrypoint.prod.sh
    volumes:
      - static:/vol/web
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - static:/vol/web
      - ./nginx/certbot/www:/var/www/certbot/:ro
      - ./nginx/certbot/conf:/etc/nginx/ssl/:ro
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
      - PMA_DOMAIN=${PMA_DOMAIN}
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    depends_on:
      - web

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx/certbot/www:/var/www/certbot/:rw
      - ./nginx/certbot/conf:/etc/letsencrypt/:rw
      - ./nginx/certbot/log:/var/log/:rw
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8001:80
    environment:
      - PMA_HOST=${DB_HOST}
      - UPLOAD_LIMIT=${PMA_UPLOAD_LIMIT}
      - MEMORY_LIMIT=${PMA_MEMORY_LIMIT}
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

volumes:
  static: null
