version: '3.8'

services:
  web:
    build: ./app
    ports:
      - 8000:8000
      - 3000:3000
    volumes:
      - ./app:/src/app
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: mariadb
    ports:
      - 3306
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    command:
      - "--character-set-server=utf8mb4"
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASS}

volumes:
  db: null
